export default [
    {
        no: 1,
        date: '2023-02-19',
        prompt: `artstation original character, (masterpiece, Extremely detailed CG unity 8k wallpaper, best quality, highres:1.2), (ultra_detailed, UHD:1.2), (pixiv:1.3), distinct, vivid color, expressionless, unreal engine, (gradation hair), (upper body, from front:1.2), sidelighting, perfect face, detailed face , masterpiece, best quality, 1girl, red hair, red eyes, summer sailor collar, small oped mouth, blurry, blurry_background, blurry_foreground, collarbone, cover, depth_of_field, hair_acc, hair_ornament, long_hair, looking_at_viewer, motion_blur, neckerchief, red_neckerchief, sailor_collar, school_uniform, school_uniform, serafuku, smile, solo, upper_body, white_acc, white_shirt, nsfw`,
        negative: `lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,`,
        model: 'anything_4_webui',
        width: '768',
        height: '512',
        steps: '32',
        method: 'DPM++ 2M Karras',
        scale: '8',
        seed: 2655754223,
        src: './images/001.jpg',
        align: 'left',
    },
    {
        no: 2,
        date: '2023-02-17',
        prompt: `artstation original character, (masterpiece, Extremely detailed CG unity 8k wallpaper, best quality, highres:1.2), (ultra_detailed, UHD:1.2), (pixiv:1.3), distinct, vivid color, expressionless, unreal engine, (black hair), (upper body, from front:1.2), sidelighting, perfect face, detailed face, lipstick, perfect body, beautiful eyes, pretty face, (1girl:1.4), (bishoujo:1.2), looking at viewer, blunt bangs, cant be this cute, medium-large breast, (bright skin:1.4), young girl, hair ornament, (background(akihabara ):1.3), (colorful hanbok, underboob, gloves:1.3), long wavy hair, navel`,
        negative: `nsfw, Fat, ugly, blurry, blur, tanned, moles, (animal ears, horn), glasses, stain, watermark, letters, blueprints, barcodes, elf ears, (Low Quality Low-res:1.4), (Poorly Made Bad 3D, Lousy Bad Realistic:1.1), thick, clitoris, muscular, dirty, red`,
        model: '', // String,
        width: '512', // Number,
        height: '768', // Number,
        steps: '32', // Number,
        method: 'DDIM', // String,
        scale: '8', // Number,
        seed: 1295339121, // Number,
        src: './images/002.jpg',
    },
    {
        no: 3,
        date: '2023-02-19',
        prompt: 'artstation original character, (masterpiece, Extremely detailed CG unity 8k wallpaper, best quality, highres:1.2), (ultra_detailed, UHD:1.2), (pixiv:1.3), distinct, vivid color, expressionless, unreal engine, (black hair), (upper body, from front:1.2), sidelighting, perfect face, detailed face , masterpiece, best quality, 1girl, black_hair, blue_eyes, blue_sailor_collar, blurry, blurry_background, blurry_foreground, collarbone, cover, depth_of_field, flower, hair_flower, hair_ornament, long_hair, looking_at_viewer, motion_blur, neckerchief, red_neckerchief, sailor_collar, sakugawa_school_uniform, school_uniform, serafuku, smile, solo, upper_body, white_flower, white_shirt',
        negative:
            'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,',
        model: '',
        width: '768',
        height: '512',
        steps: '32',
        method: 'DPM++ 2M Karras',
        scale: '8',
        seed: 2655754185,
        src: './images/003.jpg',
    },
    {
        no: 4,
        date: '2023-02-19',
        prompt: 'artstation original character, (masterpiece, Extremely detailed CG unity 8k wallpaper, best quality, highres:1.2), (ultra_detailed, UHD:1.2), (pixiv:1.3), distinct, vivid color, expressionless, unreal engine, (black hair), (upper body, from front:1.2), sidelighting, perfect face, detailed face , masterpiece, best quality, 1girl, red hair, red eyes, summer sailor collar, blurry, blurry_background, blurry_foreground, collarbone, cover, depth_of_field, flower, hair_flower, hair_ornament, long_hair, looking_at_viewer, motion_blur, neckerchief, red_neckerchief, sailor_collar, school_uniform, school_uniform, serafuku, smile, solo, upper_body, white_flower, white_shirt, nsfw',
        negative:
            'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry',
        model: '',
        width: '768',
        height: '512',
        steps: '32',
        method: 'DPM++ 2M Karras',
        scale: '8',
        seed: 2655754203,
        src: './images/004.jpg',
    },
    {
        no: 5,
        date: '2023-02-19',
        prompt: 'artstation original character, (masterpiece, Extremely detailed CG unity 8k wallpaper, best quality, highres:1.2), (ultra_detailed, UHD:1.2), (pixiv:1.3), distinct, vivid color, expressionless, unreal engine, (black gradation hair), (upper body, from front:1.2), sidelighting, perfect face, detailed face , masterpiece, best quality, 1girl, red hair, red eyes, summer sailor collar, small oped mouth, blurry, blurry_background, blurry_foreground, collarbone, cover, depth_of_field, hair_acc, hair_ornament, long_hair, looking_at_viewer, motion_blur, neckerchief, red_neckerchief, sailor_collar, school_uniform, school_uniform, serafuku, smile, solo, upper_body, white_acc, white_shirt, nsfw',
        negative:
            'lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry',
        model: '',
        width: '428',
        height: '926',
        steps: '32',
        method: 'DPM++ 2M Karras',
        scale: '8',
        seed: 2655754249,
        src: './images/005.jpg',
    },
    {
        no: 6,
        date: '2023-02-19',
        prompt: 'artstation original character, (masterpiece, Extremely detailed CG unity 8k wallpaper, best quality, highres:1.2), (ultra_detailed, UHD:1.2), (pixiv:1.3), distinct, vivid color, expressionless, unreal engine, (upper body, from front:1.2), 1 girl, mysterious aura, Long curly black hair, Intense glowing blue eyes, dark flowing gown, Standing atop a large rock, Tall trees reaching towards the sky, A full moon shining bright, Mystical creatures lurking in the shadows,  smile face, Holding a  magic crystal orb , breast, A small (stream) winding through the trees, blue light illuminating face, mystical symbols carved rock, night, dark, (very detailed background:1.0), (highly detailed background:1.0), masterpiece, best quality, (extremely detailed), intricate',
        negative:
            'lowres, bad anatomy, bad hands, text, error, dextra fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry,(by bad-image-v2-39000:0.9), (art by negprompt5:0.9), (far away, out of frame:1.4), negprompt lowres, signature, watermark, username, blurry, artist name, copyright name, watermark, (abstract, anatomical nonsense, simple background, white background:1.2), lowres, ((bad anatomy)), ((bad hands)), text, missing finger, extra digits, fewer digits, blurry, ((mutated hands and fingers)), (poorly drawn face), ((mutation)), ((deformed face)), (ugly), ((bad proportions)), ((extra limbs)), extra face, (double head), (extra head), ((extra feet)), monster, logo, cropped, worst quality, low quality, normal quality, jpeg, humpbacked, long body, long neck, ((jpeg artifacts)), (worst quality, low quality:1.4)',
        model: '',
        width: '768',
        height: '512',
        steps: '32',
        method: 'DDIM',
        scale: '8',
        seed: 2655754279,
        src: './images/006.jpg',
    },
    {
        no: 7,
        date: '2023-02-20',
        prompt: `(((masterpiece))), (((highres))), (((ultra-detailed))), (((illustration))), (((intricate))), (((extremely detailed))), (((soft lighting))), (((soft light))), (((soft focus))), ((1girl)), (((short hair))), (((black hair))), (((braid one's hair))), (((wearing a simple choker))), (((white coat))), (((black shirt))), ((small round breasts)), ((light brown eyes)), (((right pupil))), (((left pupil))), ((blushing)), ((smiling)), ((beautiful face)), ((looking at viewer)), white background, viewfinder`,
        negative:
            'lowres, bad anatomy, bad hands, mutated hand, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, out of focus, glowing eyes, (((multiple views))), (((bad proportions))), (((multiple legs))), (((multiple arms))), 3D, bad_prompt, (worst quality:2.0), (low quality:2.0), inaccurate limb, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, tall, (painting by bad-artist-anime:0.9), (painting by bad-artist:0.9), bad-prompt:0.5, watermark, text, error, blurry, jpeg artifacts, cropped, normal quality, jpeg artifacts, signature, watermark, username, artist name, (worst quality, low quality:1.4), bad anatomy, low quality lowres, low quality lowres low polygon 3D game, low quality lowres',
        model: 'anything_4_webui',
        width: '768',
        height: '512',
        steps: '32',
        method: 'DPM++ 2M Karras',
        scale: '8',
        seed: 1859708861,
        src: './images/007.jpg',
    },
    {
        no: 8,
        date: '2023-02-20',
        prompt: `(((masterpiece))), (((highres))), (((ultra-detailed))), (((illustration))), (((intricate))), (((extremely detailed))), (((soft lighting))), (((soft light))), (((soft focus))), ((1girl)), (((short hair))), (((black hair))), (((braid one's hair))), (((wearing a simple choker))), (((white coat))), (((black shirt))), ((small round breasts)), ((light brown eyes)), (((right pupil))), (((left pupil))), ((blushing)), ((smiling)), ((beautiful face)), ((looking at viewer)), white background, viewfinder`,
        negative:
            'lowres, bad anatomy, bad hands, mutated hand, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, out of focus, glowing eyes, (((multiple views))), (((bad proportions))), (((multiple legs))), (((multiple arms))), 3D, bad_prompt, (worst quality:2.0), (low quality:2.0), inaccurate limb, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, tall, (painting by bad-artist-anime:0.9), (painting by bad-artist:0.9), bad-prompt:0.5, watermark, text, error, blurry, jpeg artifacts, cropped, normal quality, jpeg artifacts, signature, watermark, username, artist name, (worst quality, low quality:1.4), bad anatomy, low quality lowres, low quality lowres low polygon 3D game, low quality lowres',
        model: 'anything_4_webui',
        width: '768',
        height: '512',
        steps: '32',
        method: 'DPM++ 2M Karras',
        scale: '8',
        seed: 1859708879,
        src: './images/008.jpg',
    },
    {
        no: 9,
        date: '2023-02-20',
        prompt: `(((masterpiece))), (((highres))), (((ultra-detailed))), (((illustration))), (((intricate))), (((extremely detailed))), (((soft lighting))), (((soft light))), (((soft focus))), ((1girl)), (((short hair))), (((black hair))), (((braid one's hair))), (((wearing a simple choker))), (((white coat))), (((black shirt))), ((small round breasts)), ((light brown eyes)), (((right pupil))), (((left pupil))), ((blushing)), ((smiling)), ((beautiful face)), ((looking at viewer)), white background, viewfinder`,
        negative:
            'lowres, bad anatomy, bad hands, mutated hand, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, out of focus, glowing eyes, (((multiple views))), (((bad proportions))), (((multiple legs))), (((multiple arms))), 3D, bad_prompt, (worst quality:2.0), (low quality:2.0), inaccurate limb, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, tall, (painting by bad-artist-anime:0.9), (painting by bad-artist:0.9), bad-prompt:0.5, watermark, text, error, blurry, jpeg artifacts, cropped, normal quality, jpeg artifacts, signature, watermark, username, artist name, (worst quality, low quality:1.4), bad anatomy, low quality lowres, low quality lowres low polygon 3D game, low quality lowres',
        model: 'anything_4_webui',
        width: '768',
        height: '512',
        steps: '32',
        method: 'DPM++ 2M Karras',
        scale: '8',
        seed: 1859708885,
        src: './images/009.jpg',
    },
    {
        no: 10,
        date: '2023-02-20',
        prompt: `(((masterpiece))), (((highres))), (((ultra-detailed))), (((illustration))), (((intricate))), (((extremely detailed))), (((soft lighting))), (((soft light))), (((soft focus))), ((1girl)), (((short hair))), (((black hair))), (((braid one's hair))), (((wearing a simple choker))), (((white coat))), (((black shirt))), ((small round breasts)), ((light brown eyes)), (((right pupil))), (((left pupil))), ((blushing)), ((smiling)), ((beautiful face)), ((looking at viewer)), white background, viewfinder`,
        negative:
            'lowres, bad anatomy, bad hands, mutated hand, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, out of focus, glowing eyes, (((multiple views))), (((bad proportions))), (((multiple legs))), (((multiple arms))), 3D, bad_prompt, (worst quality:2.0), (low quality:2.0), inaccurate limb, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, tall, (painting by bad-artist-anime:0.9), (painting by bad-artist:0.9), bad-prompt:0.5, watermark, text, error, blurry, jpeg artifacts, cropped, normal quality, jpeg artifacts, signature, watermark, username, artist name, (worst quality, low quality:1.4), bad anatomy, low quality lowres, low quality lowres low polygon 3D game, low quality lowres',
        model: 'anything_4_webui',
        width: '768',
        height: '512',
        steps: '32',
        method: 'DPM++ 2M Karras',
        scale: '8',
        seed: 1859708895,
        src: './images/010.jpg',
    },
    {
        no: 11,
        date: '2023-02-20',
        prompt: `(((masterpiece))), (((highres))), (((ultra-detailed))), (((illustration))), (((intricate))), (((extremely detailed))), (((soft lighting))), (((soft light))), (((soft focus))), ((1girl)), (((short hair))), (((black hair))), (((braid one's hair))), (((wearing a simple choker))), (((white coat))), (((black shirt))), ((small round breasts)), ((light brown eyes)), (((right pupil))), (((left pupil))), ((blushing)), ((smiling)), ((beautiful face)), ((looking at viewer)), white background, viewfinder`,
        negative:
            'lowres, bad anatomy, bad hands, mutated hand, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, out of focus, glowing eyes, (((multiple views))), (((bad proportions))), (((multiple legs))), (((multiple arms))), 3D, bad_prompt, (worst quality:2.0), (low quality:2.0), inaccurate limb, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, tall, (painting by bad-artist-anime:0.9), (painting by bad-artist:0.9), bad-prompt:0.5, watermark, text, error, blurry, jpeg artifacts, cropped, normal quality, jpeg artifacts, signature, watermark, username, artist name, (worst quality, low quality:1.4), bad anatomy, low quality lowres, low quality lowres low polygon 3D game, low quality lowres',
        model: 'anything_4_webui',
        width: '768',
        height: '512',
        steps: '32',
        method: 'DPM++ 2M Karras',
        scale: '8',
        seed: 1859708917,
        src: './images/011.jpg',
    },
    {
        no: 12,
        date: '2023-02-24',
        prompt: `(masterpiece, best quality, ultra-detailed), (((detailed background, bloom, depth of field))), (best illumination, an extremely delicate and beautiful), detailed scenery, dramatic light, colorful, ((realistic)), hyper detail, finely detailed eyes and detailed face, (1girl, solo,sharp_face, orange hair, spiky long hair, hair, red_eyes, red hero armor, Flower_earrings, ((many swords around)), ((magic circle)), intricate details, focus_face`,
        negative:
            'HyperStylizeV6,bad face, bad anatomy, bad proportions, bad perspective, multiple views, concept art, reference sheet, mutated hands and fingers, interlocked fingers, twisted fingers, excessively bent fingers, more than five fingers, lowres, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, low quality lowres multiple breasts, low quality lowres mutated hands and fingers, more than two arms, more than two hands, more than two legs, more than two feet, low quality lowres long body, low quality lowres mutation poorly drawn, low quality lowres black-white, low quality lowres bad anatomy, low quality lowres liquid body',
        model: 'anything_4',
        width: '768',
        height: '512',
        steps: '60',
        method: 'Euler a',
        scale: '8',
        seed: 3962032498,
        src: './images/012.jpg',
    },
    {
        no: 13,
        date: '2023-02-24',
        prompt: `(masterpiece, best quality, ultra-detailed), (((detailed background, bloom, depth of field))), (best illumination, an extremely delicate and beautiful), detailed scenery, dramatic light, colorful, ((realistic)), hyper detail, finely detailed eyes and detailed face, (1girl, solo,sharp_face, orange hair, spiky long hair, hair, red_eyes, red hero armor, Flower_earrings, ((many swords around)), ((magic circle)), intricate details, focus_face`,
        negative:
            'HyperStylizeV6,bad face, bad anatomy, bad proportions, bad perspective, multiple views, concept art, reference sheet, mutated hands and fingers, interlocked fingers, twisted fingers, excessively bent fingers, more than five fingers, lowres, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, low quality lowres multiple breasts, low quality lowres mutated hands and fingers, more than two arms, more than two hands, more than two legs, more than two feet, low quality lowres long body, low quality lowres mutation poorly drawn, low quality lowres black-white, low quality lowres bad anatomy, low quality lowres liquid body',
        model: 'anything_4',
        width: '768',
        height: '512',
        steps: '60',
        method: 'Euler a',
        scale: '8',
        seed: 3962032515,
        src: './images/013.jpg',
    },
    {
        no: 14,
        date: '2023-02-24',
        prompt: `(masterpiece, best quality, ultra-detailed), (((detailed background, bloom, depth of field))), (best illumination, an extremely delicate and beautiful), detailed scenery, dramatic light, colorful, ((realistic)), hyper detail, finely detailed eyes and detailed face, (1girl, solo,sharp_face, orange hair, spiky long hair, hair, red_eyes, red hero armor, Flower_earrings, ((many swords around)), ((magic circle)), intricate details, focus_face`,
        negative:
            'HyperStylizeV6,bad face, bad anatomy, bad proportions, bad perspective, multiple views, concept art, reference sheet, mutated hands and fingers, interlocked fingers, twisted fingers, excessively bent fingers, more than five fingers, lowres, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, low quality lowres multiple breasts, low quality lowres mutated hands and fingers, more than two arms, more than two hands, more than two legs, more than two feet, low quality lowres long body, low quality lowres mutation poorly drawn, low quality lowres black-white, low quality lowres bad anatomy, low quality lowres liquid body',
        model: 'anything_4',
        width: '768',
        height: '512',
        steps: '60',
        method: 'Euler a',
        scale: '8',
        seed: 3962032515,
        src: './images/014.jpg',
    },
    {
        no: 15,
        date: '2023-02-24',
        prompt: `(masterpiece, best quality, ultra-detailed), (((detailed background, bloom, depth of field))), (best illumination, an extremely delicate and beautiful), detailed scenery, dramatic light, colorful, ((realistic)), hyper detail, finely detailed eyes and detailed face, (1girl, solo,sharp_face, orange hair, spiky long hair, hair, red_eyes, red hero armor, Flower_earrings, ((many swords around)), ((magic circle)), intricate details, focus_face`,
        negative:
            'HyperStylizeV6,bad face, bad anatomy, bad proportions, bad perspective, multiple views, concept art, reference sheet, mutated hands and fingers, interlocked fingers, twisted fingers, excessively bent fingers, more than five fingers, lowres, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, low quality lowres multiple breasts, low quality lowres mutated hands and fingers, more than two arms, more than two hands, more than two legs, more than two feet, low quality lowres long body, low quality lowres mutation poorly drawn, low quality lowres black-white, low quality lowres bad anatomy, low quality lowres liquid body',
        model: 'anything_4',
        width: '768',
        height: '512',
        steps: '40',
        method: 'DPM++ 2M Karras',
        scale: '8',
        seed: 3962032591,
        src: './images/015.jpg',
    },
];
